[platformio]
default_envs = cyd

[env:cyd]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 460800
upload_port = COM12
monitor_port = COM12
test_framework = unity
test_port = COM12
test_speed = 115200
lib_deps =
  bodmer/TFT_eSPI@2.5.43
  bblanchon/ArduinoJson@7.4.2
  bitbank2/JPEGDEC@1.8.2
  tzapu/WiFiManager@2.0.17
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
  https://github.com/ricmoo/QRCode.git#v0.0.1
build_flags =
  -std=gnu++17
  -D USER_SETUP_LOADED=1
  -D ILI9341_2_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=21
  -D TFT_BACKLIGHT_ON=HIGH
  -D TFT_INVERSION_ON=1
  -D TOUCH_CS=33
  -D TOUCH_IRQ=36
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D LOAD_GFXFF=1
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=16000000
  -D USE_HSPI_PORT=1
  -D SUPPORT_TRANSACTIONS=1
build_unflags =
  -std=gnu++11

[env:native]
platform = native
test_framework = unity
test_build_src = no
lib_deps =
  throwtheswitch/Unity@2.6.1
build_flags =
  -std=c++17
build_src_filter =
  +<../lib/CoreLogic/src/>
